app = "proyecto-titulo"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[deploy]
  strategy = "rolling"

[machines]
  vm_size = "shared-cpu-1x"   # tipo de CPU (1 CPU compartida)
  count = 1                   # cantidad de instancias
  memory_mb = 256             # cantidad de RAM

[build]
  dockerfile = "Dockerfile"